services:
  postgresql:
    build:
        context: ./db
        dockerfile: Dockerfile
    ports:
      - "5432:5432"
    networks:
      mynetwork:
    environment:
      - TZ=Europe/Moscow
  segmentify:
    build: .
    depends_on:
      - postgresql
    ports:
      - "9090:9090"
    networks:
      mynetwork:
    environment:
      - TZ=Europe/Moscow
      - DB_CONNECTION_STRING=user=postgres dbname=postgres host=host.docker.internal port=5432 sslmode=disable

networks:
  mynetwork:
    driver: bridge